---
title: "Lecture X - Inference with Two Sample Means"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# X. Inference with Two Sample Means

1. Logic of two-sample inference
2. Sampling distribution of mean differences
3. Independent-samples hypothesis testing
4. Non-independent-samples hypothesis testing

## Logic of Two-Sample Inference
* In hypothesis testing with two sample means, we want to know how two groups differ with respect to some outcome of interest. Our research question with two-population hypothesis testing is this: Are these two samples drawn from a single population with mean $\mu$, or are they subsets of two different populations with means $\mu_{1}$ and $\mu_{2}$, respectively? Recall from our discussion of single-sample inference that there are two possible answers to this question.
    - Yes, our samples are drawn from a single population (with respect to the outcome we are interested in). Thus, the observed difference between the two sample means reflects a chance difference, a result of random sampling error. 
    - No, our samples are drawn from two different populations. Thus, the observed difference between the two sample means reflects a systematic difference, a result of the fact that they actually comprise two different populations with respect to the outcome.
    
## Sampling Distribution of Mean Differences
* Using probability theory, we can ask how likely it is that we would observe the difference between the two sample means if the population means are actually equal. We want to know if the difference is random or systematic. With this type of question, we resort to a new sampling or probability distribution, known as the sampling distribution of mean differences. 

* In order to understand what a sampling distribution of mean differences is, let's conduct a thought experiment. Let's say that we draw a sample of males and a sample of females, ask them how many offenses they committed in the last year, calculate the mean number of offenses for each sample, and compute the difference between these two sample means ($\overline{\text{x}}_{1}-\overline{\text{x}}_{2}$). Now, imagine that we continue to do this for an infinite number of samples, calculating a mean for each sample and taking the difference between the two means. This process results in a theoretical sampling distribution of differences between sample means. This distribution is defined by two parameters.

    - The mean of this sampling distribution is $\mu_{\overline{\text{x}}_{1}}-\mu_{\overline{\text{x}}_{2}}$, and is equal to the true difference between the population means, $\mu_{1}-\mu_{2}$. 
    
    - The standard deviation of this sampling distribution is $\displaystyle \sigma_{\overline{\text{x}}_{1}-\overline{\text{x}}_{2}}=\sqrt{\frac{\sigma^{2}_{1}}{\text{n}_{1}}+\frac{\sigma^{2}_{2}}{\text{n}_{2}}}$, and is called the standard error of the difference between means, or the "standard error of the difference" for short. 

* When we are considering the sampling distribution of mean differences, we may resort to an important theorem with which we are already familiar: the central limit theorem. That is, no matter the shape of the two population distributions, when the sample sizes become large (generally over 50 each) the sampling distribution of mean differences approximates a normal distribution. This theorem implies that we may conduct hypothesis tests for two population means. 

    - Note that the general form for a standard score is the following: $$z=\frac{\text{estimate-parameter}}{\text{standard deviation}}$$ We can use this general notation to construct the standard score for mean differences: $$\displaystyle z=\frac{(\overline{\text{x}}_{1}-\overline{\text{x}}_{2})-(\mu_{1}-\mu_{2})}{\sigma_{\overline{\text{x}}_{1}-\overline{\text{x}}_{2}}}=\frac{(\overline{\text{x}}_{1}-\overline{\text{x}}_{2})-(\mu_{1}-\mu_{2})}{\sqrt{\frac{\sigma^{2}_{1}}{\text{n}_{1}}+\frac{\sigma^{2}_{2}}{\text{n}_{2}}}}$$ Since, under the null hypothesis, the population means are equivalent, we can remove the second term from the numerator. Thus, when both ??1 and ??2 are known, this leaves us with having to estimate: $$\displaystyle z=\frac{(\overline{\text{x}}_{1}-\overline{\text{x}}_{2})}{\sqrt{\frac{\sigma^{2}_{1}}{\text{n}_{1}}+\frac{\sigma^{2}_{2}}{\text{n}_{2}}}}$$ Unfortunately, the population standard deviations will not always be known. This requires us to make an adjustment to the formula by substituting the sample standard deviations for the population standard deviations, and by adjusting for the "degrees of freedom" from each sample. In this case, the test statistic becomes: $$\displaystyle t=\frac{(\overline{\text{x}}_{1}-\overline{\text{x}}_{2})-(\mu_{1}-\mu_{2})}{\sqrt{\frac{s^{2}_{1}}{\text{n}_{1}-1}+\frac{s^{2}_{2}}{\text{n}_{2}-1}}}$$

\newpage

## Independent-Samples Hypothesis Testing 

Let's pose a couple of research questions to practice hypothesis testing. 

* Suppose we want to test the association between social disorganization and violent victimization. We gather data on 41 low-SES neighborhoods and find that the mean number of victimizations in the last year is 12.4 ($\sigma^{2}$ = 18.49). We also gather data on 21 high-SES neighborhoods and find that the mean number of We also gather data on 21 high-SES neighborhoods and find that the mean number of victimizations is 5.2 ($\sigma^{2}$ = 2.25). Our research question is: Do people that live in low-SES neighborhoods have a different risk of victimization than people that live in high-SES neighborhoods? Use $\alpha$ = .01. 
    1. *Formally state hypotheses*: $\text{H}_{1}:\mu_{L} \ne \mu_{H} \therefore \mu_{L}-\mu_{H} \ne 0$; $\text{H}_{0}:\mu_{L} = \mu_{H} \therefore \mu_{L}-\mu_{H} = 0$ 
    2. *Obtain probability distribution*: z-distribution
    3. *Make decision rules*: $\alpha$=.01 (two-tailed), $z_{crit}=$, reject $\text{H}_{0}$ if |TS|>2.58. 
    \vspace{2pt}
    4. *Calculcate the test statistic*: $\displaystyle z=\frac{(\overline{\text{x}}_{1}-\overline{\text{x}}_{2})}{\sqrt{\frac{\sigma^{2}_{1}}{\text{n}_{1}}+\frac{\sigma^{2}_{2}}{\text{n}_{2}}}}$ = $\displaystyle       \frac{12.4-5.2}{\sqrt{\frac{18.49}{41}+\frac{2.25}{21}}}$ = `r format((12.4-5.2)/((sqrt((18.49/41)+(2.25/21)))),nsmall=3,digits=3)`
    5. *Make a decision about the null hypothesis*: Reject $\text{H}_{0}$, low-SES and high-SES neighborhoods have significantly different rates of victimization. 

\vspace{8pt}    

*	Prior research indicates that working youths are more heavily involved in delinquency, substance use, and other problem behaviors than non-working youths. We have a sample of 2243 working youths and find that the mean number of self-report problem behaviors is $\overline{x}_{W}$=3.73  ($\text{s}^{2}$ = 12.95). We also have a sample of 6679 non-working youths and find that the mean number of problem behaviors is $\overline{x}_{N}$=2.22 ($\text{s}^{2}$ = 8.19). Our research question is: Do working youths do engage in more problem behavior than non-working youths? Use $\alpha$ = .05.
\vspace{3pt}
    1. *Formally state hypotheses*: $\text{H}_{1}:\mu_{W} > \mu_{N} \therefore \mu_{W}-\mu_{N} > 0$; $\text{H}_{0}:\mu_{W} = \mu_{N} \therefore \mu_{W}-\mu_{N} \le 0$ 
    2. *Obtain probability distribution*: t-distribution, df=`r 2243+6679-2`
    3. *Make decision rules*: $\alpha$=.05 (one-tailed), $t_{crit}=`r format(abs(qt(.05,2243+6679-2)),nsmall=3,digits=3)`$, reject $\text{H}_{0}$ if TS>`r format(abs(qt(.05,2243+6679-2)),nsmall=3,digits=3)`. 
    \vspace{2pt}
    4. *Calculcate the test statistic*: $\displaystyle t=\frac{(\overline{\text{x}}_{1}-\overline{\text{x}}_{2})}{\sqrt{\frac{s^{2}_{1}}{\text{n}_{1}-1}+\frac{s^{2}_{2}}{\text{n}_{2}-1}}}$ = $\displaystyle \frac{3.73-2.22}{\sqrt{\frac{12.95}{2243-1}+\frac{8.19}{6679-1}}}$ = `r format((3.73-2.22)/((sqrt((12.95/(2243-1))+(8.19/(6679-1))))),nsmall=3,digits=3)`
    5. *Make a decision about the null hypothesis*: Reject $\text{H}_{0}$, working youths commit significantly more crimes than non-working youths. 
    
\newpage

*	There is some suggestion that individuals who engage in more criminal behavior are, for a variety of reasons, also more likely to be victims of crime. You compare a sample of 10 self-report high-rate offenders with 10 self-report non-offenders on the number of times in the last five years they have been the victim of a personal crime. Use $\alpha$ = .10 to test the hypothesis that a "criminal lifestyle"" increases the likelihood of victimization. 
    
\begin{table}[h]
\centering
\begin{tabular}{cccc}
\hline
$\text{x}_{C}$  & $\text{x}_{C}^{2}$  & $\text{x}_{N}$  & $\text{x}_{N}^{2}$  \\ \hline
5               & `r 5^2`             & 3               & `r 3^2`             \\
8               & `r 8^2`             & 5               & `r 5^2`             \\
10              & `r 10^2`            & 2               & `r 2^2`             \\
8               & `r 8^2`             & 8               & `r 8^2`             \\
6               & `r 6^2`             & 2               & `r 2^2`             \\
5               & `r 5^2`             & 4               & `r 4^2`             \\
2               & `r 2^2`             & 3               & `r 3^2`             \\
7               & `r 7^2`             & 1               & `r 1^2`             \\
3               & `r 3^2`             & 0               & `r 0^2`             \\
5               & `r 5^2`             & 0               & `r 0^2`             \\ \hline
$\sum{\text{x}_{C}}=`r 5+8+10+8+6+5+2+7+3+5`$  & $\sum{\text{x}_{C}^{2}}=`r 5^2+8^2+10^2+8^2+6^2+5^2+2^2+7^2+3^2+5^2`$  & $\sum{\text{x}_{N}}=`r 3+5+2+8+2+4+3+1+0+0`$  & $\sum{\text{x}_{N}^{2}}=`r 3^2+5^2+2^2+8^2+2^2+4^2+3^2+1^2+0^2+0^2`$ \\
$\overline{\text{x}}_{C}= `r (5+8+10+8+6+5+2+7+3+5)/10`$  & $\text{s}_{C}^{2}=`r ((5^2+8^2+10^2+8^2+6^2+5^2+2^2+7^2+3^2+5^2)/10)-5.9^2`$  & $\overline{\text{x}}_{N}=`r (3+5+2+8+2+4+3+1+0+0)/10`$  & $\text{s}_{N}^{2}=`r ((3^2+5^2+2^2+8^2+2^2+4^2+3^2+1^2+0^2+0^2)/10)-2.8^2`$  \\ \hline
\end{tabular}
\end{table}
    \vspace{3pt}
    
1. *Formally state hypotheses*: $\text{H}_{1}:\mu_{C} > \mu_{N} \therefore \mu_{C}-\mu_{N} > 0$; $\text{H}_{0}:\mu_{C} = \mu_{N} \therefore \mu_{C}-\mu_{N} \le 0$ 
2. *Obtain probability distribution*: t-distribution; df=$10+10-2=`r 10+10-2`$
3. *Make decision rules*: $\alpha$=.10 (one-tailed), $t_{crit}=`r format(abs(qt(.10,10+10-2)),nsmall=3,digits=3)`$, reject $\text{H}_{0}$ if TS>`r format(abs(qt(.10,10+10-2)),nsmall=3,digits=3)`. 
\vspace{2pt}
4. *Calculcate the test statistic*: $\displaystyle t=\frac{(\overline{\text{x}}_{1}-\overline{\text{x}}_{2})}{\sqrt{\frac{s^{2}_{1}}{\text{n}_{1}-1}+\frac{s^{2}_{2}}{\text{n}_{2}-1}}}$ = $\displaystyle \frac{5.9-2.8}{\sqrt{\frac{5.29}{10-1}+\frac{5.36}{10-1}}}$ = `r format((5.9-2.8)/((sqrt((5.29/(10-1))+(5.36/(10-1))))),nsmall=3,digits=3)`
5. *Make a decision about the null hypothesis*: Reject $\text{H}_{0}$, people who engage in crime at a high rate are significantly more likely to have been victimized. 
    
\vspace{8pt}
* You collect data from a sample of 8 youths that report having gone out on a date in the last year, and a sample of 6 youths that report not having gone out on a date. Each youth provides information on their self-report engagement in a variety of problem behaviors. Using $\alpha$ = .01, test the hypothesis that dating increases delinquency. 

\begin{table}[h]
\centering
\begin{tabular}{cccc}
\hline
$\text{x}_{N}$  & $\text{x}_{N}^{2}$  & $\text{x}_{D}$  & $\text{x}_{D}^{2}$  \\ \hline
1               & `r 1^2`             & 3               & `r 3^2`             \\
3               & `r 3^2`             & 1               & `r 1^2`             \\
2               & `r 2^2`             & 5               & `r 5^2`             \\
3               & `r 3^2`             & 2               & `r 2^2`             \\
0               & `r 0^2`             & 1               & `r 1^2`             \\
1               & `r 1^2`             & 0               & `r 0^2`             \\
                &                     & 3               & `r 3^2`             \\
                &                     & 4               & `r 4^2`             \\ \hline
$\sum{\text{x}_{N}}=`r 1+3+2+3+0+1`$  & $\sum{\text{x}_{N}^{2}}=`r 1^2+3^2+2^2+3^2+0^2+1^2`$  & $\sum{\text{x}_{D}}=`r 3+1+5+2+1+0+3+4`$  & $\sum{\text{x}_{D}^{2}}=`r 3^2+1^2+5^2+2^2+1^2+0^2+3^2+4^2`$ \\
$\overline{\text{x}}_{N}= `r format((1+3+2+3+0+1)/6,nsmall=2,digits=2)`$  & $\text{s}_{N}^{2}=`r format(((1^2+3^2+2^2+3^2+0^2+1^2)/6)-1.67^2,nsmall=2,digits=2)`$  & $\overline{\text{x}}_{D}=`r format((3+1+5+2+1+0+3+4)/8,nsmall=2,digits=2)`$  & $\text{s}_{D}^{2}=`r format(((3^2+1^2+5^2+2^2+1^2+0^2+3^2+4^2)/8)-2.38^2,nsmall=2,digits=2)`$  \\ \hline
\end{tabular}
\end{table}

\vspace{3pt}

1. *Formally state hypotheses*: $\text{H}_{1}:\mu_{N} \ne \mu_{D} \therefore \mu_{N}-\mu_{D} \ne 0$; $\text{H}_{0}:\mu_{N} = \mu_{D} \therefore \mu_{N}-\mu_{D} = 0$ 
2. *Obtain probability distribution*: t-distribution; df=$6+8-2=`r 6+8-2`$
3. *Make decision rules*: $\alpha$=.01 (one-tailed), $t_{crit}=`r format(abs(qt(.01,8+6-2)),nsmall=3,digits=3)`$, reject $\text{H}_{0}$ if TS<`r format((qt(.01,8+6-2)),nsmall=3,digits=3)`. 
\vspace{2pt}
4. *Calculcate the test statistic*: $\displaystyle t=\frac{(\overline{\text{x}}_{1}-\overline{\text{x}}_{2})}{\sqrt{\frac{s^{2}_{1}}{\text{n}_{1}-1}+\frac{s^{2}_{2}}{\text{n}_{2}-1}}}$ = $\displaystyle            \frac{1.67-2.38}{\sqrt{\frac{1.21}{6-1}+\frac{2.46}{8-1}}}$ = `r format((1.67-2.38)/((sqrt((1.21/(6-1))+(2.46/(8-1))))),nsmall=3,digits=3)`
5. *Make a decision about the null hypothesis*: Accept $\text{H}_{0}$, youth who date do not engage in more problem behaviors than youth who do not date. 

\newpage

## Non-Independent Samples Hypothesis Testing

* There is one very important assumption that must be met in order to carry out the hypothesis tests that we just completed. Our two samples must be independent of one another. In other words, both samples are randomly selected, and the fact that one case is selected into one sample does not affect the selection of a different case into the other sample. From our example, we know that selecting a worker into one sample had no effect on the probability of selecting a non-worker into the other sample. Thus, our samples of workers and non-workers were each independent of the other.

* There are times when this condition is deliberately violated. The most common is when we have a "before-and-after"" design, in which we measure the dependent variable for each case at two points in time. During these two measurement periods, we typically introduce some sort of treatment, which we think of as the independent variable. What we are interested in finding out is whether the treatment had any effect on the outcome. 

* Another instance in which we have non-independent samples is when we match individuals from two samples on important characteristics, such as when we match treatment and control groups on the basis of age, gender, and race. 

* With this type of design, we must reformulate our statistical test to be based on the difference between the scores for each pair of observations. Thus, unlike the independent-samples hypothesis test, in which we test the difference between two sample means (i.e., $\overline{\text{x}}_{1}-\overline{\text{x}}_{2}$), with a non-independent-samples hypothesis test, we test the difference between the pair of raw scores for each individual (i.e., $\text{x}_{1}-\text{x}_{2}$). The sample size is not the total number of observations in each group, but rather the number of pairs of observations. 

* The question we want to ask with a non-independent-samples hypothesis test is: Did the treatment have an effect on the outcome, or do the matched groups differ with respect to the outcome? We want to use a formula that takes into account that we are computing differences between raw scores. When we do this, we obtain: $$TS=\frac{\overline{\text{x}}_{D}-\mu_{D}}{\sqrt{\text{s}^{2}_{D}/\text{n}-1}} = \frac{\overline{\text{x}}_{D}-\mu_{D}}{\text{s}_{D}/\sqrt{\text{n}-1}}$$ However, under the null hypothesis, we assume the treatment had no effect, which means the $\mu_{D}=0$. This means that we can remove this term from the forumla, which leaves us with: $$TS=\frac{\overline{\text{x}}_{D}-\mu_{D}}{\text{s}_{D}/\sqrt{\text{n}-1}} \text{ where } \overline{x}_{D}=\frac{\sum{\text{x}_{2}-\text{x}_{1}}}{n} \text{ and } \text{s}_{D}=\sqrt{\frac{\sum{(\text{x}_{2}-\text{x}_{1})}}{n}}=\sqrt{\frac{\sum{\text{x}^{2}_{D}}}{n}-\overline{\text{x}}^{2}_{D}}$$

\newpage

Let's work through a couple of examples.

* There is evidence that children with criminal parents are more likely to be criminal themselves that children with non-criminal parents. You collect data on a sample of 121 youths who have at least one parent with an official record of conviction, and match them on the basis of age, sex, race, and school performance with 121 youths whose parents do not have a record of conviction. You find that the mean difference ($\text{x}_{D}=\text{x}_{2}-\text{x}_{1}=\text{x}_{C}-\text{x}_{N}$) between these matched groups is 5.75 ($\text{s}_{D} = 4.25$). Your research question is as follows: Are youths with criminal parents more likely to be arrested than youths without criminal parents? Use $\alpha$ = .01.

    1. *Formally state hypotheses*: $\text{H}_{1}:\mu_{D} < 0$; $\text{H}_{0}:\mu_{D} \ge 0$ 
    2. *Obtain probability distribution*: t-distribution; df=$10-1=`r 10-1`$
    3. *Make decision rules*: $\alpha$=.01 (one-tailed), $t_{crit}=`r format(abs(qt(.01,121-1)),nsmall=3,digits=3)`$, reject $\text{H}_{0}$ if TS>`r format(abs(qt(.01,121-1)),nsmall=3,digits=3)`. 
    \vspace{2pt}
    4. *Calculcate the test statistic*: $\displaystyle t=\frac{\overline{\text{x}}_{D}-\mu_{D}}{\text{s}_{D}/\sqrt{\text{n}-1}}=\frac{5.75}{4.25/\sqrt{121-1}}$ = `r format(5.75/(4.25/sqrt(121-1)),nsmall=3,digits=3)`
    5. *Make a decision about the null hypothesis*: Reject $\text{H}_{0}$, having criminal parents significantly increases the likelihood of being arrested. 
    
* We want to know if formal sanctions deter crime. We draw a sample of $n$=10 offenders and ask them the number of arrests they had prior to appearing in court. We then ask them the number of arrests they had after they appeared in court. Use $\alpha$ = .05 to test the hypothesis that formal sanctions deter crime. 
\begin{table}[h]
\centering
\begin{tabular}{cccc}
\hline
$\text{x}_{1}$  & $\text{x}_{2}$  & $\text{x}_{D}=\text{x}_{2}-\text{x}_{1}$  & $\text{x}^{2}_{D}$  \\ \hline
3               & 1               & -2                                        & 4                   \\
2               & 2               & 0                                         & 0                   \\
1               & 0               & -1                                        & 1                   \\
1               & 1               & 0                                         & 0                   \\
2               & 1               & -1                                        & 1                   \\
4               & 4               & 0                                         & 0                   \\
6               & 6               & 0                                         & 0                   \\
1               & 0               & -1                                        & 1                   \\
1               & 1               & 0                                         & 0                   \\
2               & 3               & -1                                        & 1                   \\ \hline
$\overline{x}_{1}=`r (3+2+1+1+2+4+6+1+2)/10`$ & $\overline{x}_{1}=`r (1+2+0+1+1+4+6+0+3)/10`$ & $\sum{\text{x}_{D}}=`r -2+0+-1+0+-1+0+0+-1+0+1`$  & $\sum{x}^{2}_{D}=`r 4+0+1+0+1+0+0+1+0+1`$ \\
                                              &                                               & $\overline{x}_{D}=`r (-2+0+-1+0+-1+0+0+-1+0+1)/10`$  & $\text{s}_{D}=\sqrt{\frac{8}{10}-.40^{2}}=`r format((sqrt((8/10)-.40^2)),nsmall=2,digits=2)`$ \\ \hline
\end{tabular}
\end{table}
    1. *Formally state hypotheses*: $\text{H}_{1}:\mu_{D} < 0$; $\text{H}_{0}:\mu_{D} \ge 0$ 
    2. *Obtain probability distribution*: t-distribution; df=$10-1=`r 10-1`$
    3. *Make decision rules*: $\alpha$=.05 (one-tailed), $t_{crit}=`r format(abs(qt(.05,10-1)),nsmall=3,digits=3)`$, reject $\text{H}_{0}$ if TS<`r format((qt(.05,10-1)),nsmall=3,digits=3)`. 
    \vspace{2pt}
    4. *Calculcate the test statistic*: $\displaystyle t=\frac{\overline{\text{x}}_{D}-\mu_{D}}{\text{s}_{D}/\sqrt{\text{n}-1}}=\frac{-0.40}{.80/\sqrt{10-1}}$ = `r format(-0.40/(.80/sqrt(10-1)),nsmall=3,digits=3)`
    5. *Make a decision about the null hypothesis*: Accept $\text{H}_{0}$, formal adjudication does not appear to deter crime. 

\newpage

* Suppose that we have a sample of five high-risk middle-school students with a history of poor academic performance. In order to help them improve, the school implements an after-school tutoring program. Their test scores before and after participation in the program are listed below. Use $\alpha$ = .05 to test the hypothesis that the program is effective in raising test scores.
\begin{table}[h]
\centering
\begin{tabular}{cccc}
\hline
$\text{x}_{1}$  & $\text{x}_{2}$  & $\text{x}_{D}=\text{x}_{2}-\text{x}_{1}$  & $\text{x}^{2}_{D}$  \\ \hline
60              & 62              & 2                                         & 4                   \\
66              & 66              & 0                                         & 0                   \\
65              & 67              & 2                                         & 4                   \\
60              & 64              & 4                                         & 16                  \\
59              & 65              & 6                                         & 36                  \\ \hline
$\overline{x}_{1}=`r (60+66+65+60+59)/5`$ & $\overline{x}_{1}=`r (62+66+67+64+65)/5`$ & $\sum{\text{x}_{D}}=`r 2+0+2+4+6`$  & $\sum{x}^{2}_{D}=`r 4+0+4+16+36`$ \\
                                              &                                               & $\overline{x}_{D}=`r (2+0+2+4+6)/5`$  & $\text{s}_{D}=\sqrt{\frac{60}{5}-2.8^{2}}=`r format((sqrt((60/5)-2.8^2)),nsmall=2,digits=2)`$ \\ \hline
\end{tabular}
\end{table}
    1. *Formally state hypotheses*: $\text{H}_{1}:\mu_{D} > 0$; $\text{H}_{0}:\mu_{D} \le 0$ 
    2. *Obtain probability distribution*: t-distribution; df=$5-1=`r 5-1`$
    3. *Make decision rules*: $\alpha$=.05 (one-tailed), $t_{crit}=`r format(abs(qt(.05,5-1)),nsmall=3,digits=3)`$, reject $\text{H}_{0}$ if TS>`r format(abs(qt(.05,5-1)),nsmall=3,digits=3)`. 
    \vspace{2pt}
    4. *Calculcate the test statistic*: $\displaystyle t=\frac{\overline{\text{x}}_{D}-\mu_{D}}{\text{s}_{D}/\sqrt{\text{n}-1}}=\frac{2.8}{2.04/\sqrt{5-1}}$ = `r format(2.8/(2.04/sqrt(5-1)),nsmall=3,digits=3)`
    5. *Make a decision about the null hypothesis*: Reject $\text{H}_{0}$, the tutoring program significantly raised test scores. 
    
\newpage

* We saw earlier that youths who are employed are more likely to be delinquent than youths that are not employed. How about if we consider the same group of youths at two points in time, both before and after the transition to employment (the "treatment"")? If youth employment is criminogenic, we would expect that youths who begin should also increase their involvement in problem behavior. We collect data on a sample of 15 high-school students who at time one were non-workers, and who by time two were working part time. Use $\alpha$ = .05 to test the hypothesis that the transition to work is criminogenic.
\begin{table}[h]
\centering
\begin{tabular}{cccc}
\hline
$\text{x}_{1}$  & $\text{x}_{2}$  & $\text{x}_{D}=\text{x}_{2}-\text{x}_{1}$  & $\text{x}^{2}_{D}$  \\ \hline
4               & 5               & 1                                         & 1                   \\
0               & 0               & 0                                         & 0                   \\
1               & 2               & 1                                         & 1                   \\
1               & 1               & 0                                         & 0                   \\
3               & 1               & -2                                        & 4                   \\
5               & 4               & -1                                        & 1                   \\
2               & 3               & 1                                         & 1                   \\
0               & 2               & 2                                         & 4                   \\
1               & 3               & 2                                         & 4                   \\
3               & 2               & -1                                        & 1                   \\ 
2               & 1               & -1                                        & 1                   \\
3               & 5               & 2                                         & 4                   \\
5               & 5               & 0                                         & 0                   \\
3               & 4               & 1                                         & 1                   \\
2               & 5               & 3                                         & 9                   \\ \hline
$\overline{x}_{1}=`r format((4+0+1+1+3+5+2+0+1+3+2+3+5+3+2)/15,nsmall=2,digits=2)`$ & $\overline{x}_{1}=`r format((5+0+2+1+1+4+3+2+3+2+1+5+5+4+5)/15,nsmall=2,digits=2)`$ & $\sum{\text{x}_{D}}=`r 1+0+1+0+-2+-1+
1+2+2+-1+-1+2+0+1+3`$  & $\sum{x}^{2}_{D}=`r 1+0+1+0+4+1+1+4+4+1+1+4+0+1+9`$ \\
                                              &                                               & $\overline{x}_{D}=`r format((1+0+1+0+-2+-1+1+2+2+-1+-1+2+0+1+3)/15,nsmall=2,digits=2)`$  & $\text{s}_{D}=\sqrt{\frac{32}{15}-.53^{2}}=`r format((sqrt((32/15)-.53^2)),nsmall=2,digits=2)`$ \\ \hline
\end{tabular}
\end{table}
    1. *Formally state hypotheses*: $\text{H}_{1}:\mu_{D} > 0$; $\text{H}_{0}:\mu_{D} \le 0$ 
    2. *Obtain probability distribution*: t-distribution; df=$15-1=`r 15-1`$
    3. *Make decision rules*: $\alpha$=.05 (one-tailed), $t_{crit}=`r format(abs(qt(.05,15-1)),nsmall=3,digits=3)`$, reject $\text{H}_{0}$ if TS>`r format(abs(qt(.05,15-1)),nsmall=3,digits=3)`. 
    \vspace{2pt}
    4. *Calculcate the test statistic*: $\displaystyle t=\frac{\overline{\text{x}}_{D}-\mu_{D}}{\text{s}_{D}/\sqrt{\text{n}-1}}=\frac{.53}{1.36/\sqrt{15-1}}$ = `r format(.53/(1.36/sqrt(15-1)),nsmall=3,digits=3)`
    5. *Make a decision about the null hypothesis*: Accept $\text{H}_{0}$, youth employment is not criminogenic. 

